Repository alhassanmoses/TradingSystem, pull requests merged in 2021-12, with the labels that each got.

#30 Order creation feature inproved
  src/main/java/com/clientService/account/model/Account.java
  src/main/java/com/clientService/exceptions/InvalidOrderRequestException.java
  src/main/java/com/clientService/order/controller/OrderController.java
  src/main/java/com/clientService/order/model/OrderModel.java
  src/main/java/com/clientService/order/model/OrderResponse.java
  src/main/java/com/clientService/order/model/Product.java
  src/main/java/com/clientService/order/repository/OrderRepository.java
  src/main/java/com/clientService/order/service/OrderService.java
  src/main/java/com/clientService/orderExecution/model/OrderExecution.java
  src/main/java/com/clientService/user/repository/AppUserRepository.java
  src/main/java/com/clientService/user/service/AppUserService.java
Labels: priority-Medium

#34 Client order service new version
  .idea/misc.xml
  src/main/java/com/clientService/order/service/OrderService.java
  src/main/java/com/clientService/securityConfig/EmailValidation.java
  src/main/java/com/clientService/securityConfig/JWTFilter.java
  src/main/java/com/clientService/securityConfig/WebSecurityConfig.java
  src/main/java/com/clientService/user/controller/UserController.java
  src/main/java/com/clientService/user/model/HttpResponseBody.java
  src/main/java/com/clientService/user/repository/AppUserRepository.java
  src/main/java/com/clientService/user/service/AppUserAuthService.java
  src/main/java/com/clientService/user/service/AppUserService.java
  src/main/java/com/clientService/user/service/AppUserSignInService.java
  target/classes/application.yml
Labels: enhancement

#36 added logic to create user portfolio
  src/main/java/com/clientService/order/service/OrderService.java
  src/main/java/com/clientService/securityConfig/WebSecurityConfig.java
  src/main/java/com/clientService/user/controller/UserController.java
  src/main/java/com/clientService/user/service/AppUserAuthService.java
  src/main/java/com/clientService/user/service/AppUserService.java
  src/main/java/com/clientService/user/service/AppUserSignInService.java
  target/classes/application.yml
Labels: enhancement

#37 added logic to create user portfolio when user sign up, resolved stat…
  src/main/java/com/clientService/order/service/CachedMarketDataService.java
  src/main/java/com/clientService/order/service/OrderPlacingService.java
  src/main/java/com/clientService/user/service/AppUserAuthService.java
  target/classes/application.yml
Labels: enhancement

#39 Fixed all logical and dependency bugs with the order processing servi…
  pom.xml
  src/main/java/com/clientService/order/model/MarketDataProduct.java
  src/main/java/com/clientService/order/model/OrderModel.java
  src/main/java/com/clientService/order/service/CachedMarketDataService.java
  src/main/java/com/clientService/order/service/JsonRestTemplate.java
  src/main/java/com/clientService/order/service/OrderPlacingService.java
  src/main/java/com/clientService/order/service/OrderService.java
  src/main/java/com/clientService/order/service/OrderServiceHelper.java
  src/main/java/com/clientService/securityConfig/ExchangeSubscriber.java
  src/main/java/com/clientService/securityConfig/RedisConfiguration.java
  src/main/java/com/clientService/user/model/AppUser.java
  src/main/java/com/clientService/user/repository/MarketDataRepository.java
  src/main/resources/application.yml
  target/classes/application.yml
Labels: priority-High

#40 Order status tracking, orderbook and orderbook filtering feature
  src/main/java/com/clientService/error/ApiError.java
  src/main/java/com/clientService/error/CustomRestExceptionHandler.java
  src/main/java/com/clientService/error/ErrorHandler.java
  src/main/java/com/clientService/order/controller/OrderController.java
  src/main/java/com/clientService/order/model/MarketDataProduct.java
  src/main/java/com/clientService/order/model/OrderModel.java
  src/main/java/com/clientService/order/repository/OrderRepository.java
  src/main/java/com/clientService/order/service/CachedMarketDataService.java
  src/main/java/com/clientService/order/service/JsonRestTemplate.java
  src/main/java/com/clientService/order/service/OrderPlacingService.java
  src/main/java/com/clientService/order/service/OrderService.java
  src/main/java/com/clientService/order/service/OrderServiceHelper.java
  src/main/java/com/clientService/securityConfig/ExchangeSubscriber.java
  src/main/resources/application.yml
  target/classes/application.yml
Labels: priority-Medium

#44 Cancel and update order feature
  src/main/java/com/clientService/order/controller/OrderController.java
  src/main/java/com/clientService/order/service/CachedMarketDataService.java
  src/main/java/com/clientService/order/service/CancelOrderService.java
  src/main/java/com/clientService/order/service/OrderPlacingService.java
  src/main/java/com/clientService/order/service/OrderService.java
  src/main/java/com/clientService/user/model/AppUser.java
  src/main/resources/application.yml
  target/classes/application.yml
Labels: priority-Medium
